name: triggerJenkinsBuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  # Run when a pull request is merged on master
  pull_request:
    branches: [master]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: triggerJenkinsBuild
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #if: github‧event‧pull_request‧merged == true
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Access to Jenkins and run
        uses: appleboy/jenkins-action@master
        with:
          url: "https://ci.inria.fr/music/"
          user: "mathilde.merle@ihu-liryc.fr"
          # 1° Jenkins account -> Configure -> Jeton d'API (token) -> MUSICARDIOTOKEN -> keep the token value.
          # 2° Github -> Settings -> Secrets -> MUSICARDIOTOKEN -> add the previous token value.
          # 3° Jenkins -> each job needed to be run -> Configure -> "Trigger remote build" -> MUSICARDIOTOKEN
          token: ${{ secrets.MUSICARDIOTOKEN }}
          job: "music-ubuntu18-free,music-ubuntu20-free,music-macos-free,music-win-free"
          
